Repository WSUCptSCapstone-Fall2022Spring2023/wsulibraries-accessibilityapps, pull requests merged in 2022-11, with the labels that each got.

#28 Testing and acceptance plan
  Testing and Acceptance.pdf
Labels: documentation

#38 Use the pdf_extractor code to get data for the Document class
  .gitignore
  sample/__pycache__/pdf_exporter.cpython-310.pyc
  sample/setup.bat
  sample/src/__pycache__/TagTree.cpython-310.pyc
  sample/src/__pycache__/__init__.cpython-310.pyc
  sample/src/__pycache__/__init__.cpython-38.pyc
  sample/src/__pycache__/accessible_document.cpython-310.pyc
  sample/src/__pycache__/alt_text_adder.cpython-310.pyc
  sample/src/__pycache__/create_document_tags.cpython-310.pyc
  sample/src/__pycache__/document.cpython-310.pyc
  sample/src/__pycache__/document.cpython-38.pyc
  sample/src/__pycache__/document_exporter.cpython-310.pyc
  sample/src/__pycache__/document_harvester.cpython-310.pyc
  sample/src/__pycache__/document_harvester.cpython-38.pyc
  sample/src/__pycache__/document_tagger.cpython-310.pyc
  sample/src/accessible_document.py
  sample/src/document.py
  sample/src/paragraph.py
  sample/src/pdf_extractor.py
  sample/src/pdf_transform/__pycache__/alt_text_adder.cpython-310.pyc
  sample/src/pdf_transform/__pycache__/color_contrast_adder.cpython-310.pyc
  sample/src/pdf_transform/__pycache__/document_tagger.cpython-310.pyc
  sample/terminal_application.py
  tests/testOutput.html
Labels: enhancement

#41 Testing framework
  sample/__init__.py
  sample/tests/test_tag_tree.py
  sample/utils/TagTree.py
  sample/utils/__init__.py
  sample/utils/accessible_document.py
  sample/utils/document.py
  sample/utils/document_exporter.py
  sample/utils/document_harvester.py
  sample/utils/image_extractor.py
  sample/utils/paragraph.py
  sample/utils/pdf_extractor.py
  sample/utils/pdf_transform/alt_text_adder.py
  sample/utils/pdf_transform/color_contrast_adder.py
  sample/utils/pdf_transform/document_tagger.py
Labels: testing
